---
eap_admin_user: admin
eap_admin_password: passw0rd!
eap_pre_path: /opt/jboss
binary_location: http://10.0.0.10:81
jboss_home: "{{ eap_pre_path }}/jboss-eap-7.0"
eap_binary: jboss-eap-7.0.0.zip
eap_patch_binary: jboss-eap-7.0.1-patch.zip
eap_servers:
  - eap1
#  - eap2
  - master
eap_app_binary: jboss-kitchensink.war